#!/bin/bash
# =================================================================
#  SPARROWX — Universal Auto-Setup Installer (PRO VERSION)
#  Works on: Ubuntu 20.04+ / Debian 11+
#
#  Usage: sudo bash sparrow-setup.sh
# =================================================================
set -u

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOG_FILE="$SCRIPT_DIR/setup.log"

# ── Helpers ───────────────────────────────────────────────────────
log()  { echo -e "$1" | tee -a "$LOG_FILE"; }
ok()   { log "${GREEN}[✓] $1${RESET}"; }
info() { log "${CYAN}[→] $1${RESET}"; }
warn() { log "${YELLOW}[!] $1${RESET}"; }
err()  { log "${RED}[✗] $1${RESET}"; }
ask()  { echo -ne "${BOLD}$1${RESET} "; read -r "$2"; }
askd() { echo -ne "${BOLD}$1${RESET} ${DIM}[${3}]${RESET} "; read -r "$2"; eval "$2=\${$2:-$3}"; }

banner() {
  clear
  echo -e "${CYAN}${BOLD}"
  echo "  ╔══════════════════════════════════════════════════════╗"
  echo "  ║     SPARROWX — Universal Defense Stack Installer     ║"
  echo "  ║     Status: Automated / Multi-Layer / Self-Healing   ║"
  echo "  ╚══════════════════════════════════════════════════════╝"
  echo -e "${RESET}"
}

step() {
  echo ""
  echo -e "${CYAN}${BOLD}━━━ $1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
}

# ── Root check ────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run as root: sudo bash sparrow-setup.sh${RESET}"
  exit 1
fi

banner

# ── OS Detection ──────────────────────────────────────────────────
step "Detecting System"
OS_ID=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
OS_VER=$(grep '^VERSION_ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
KERNEL=$(uname -r)
ARCH=$(uname -m)
IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
RAM_GB=$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo)
CPU_CORES=$(nproc)
KERNEL_MAJOR=$(echo "$KERNEL" | cut -d. -f1)
KERNEL_MINOR=$(echo "$KERNEL" | cut -d. -f2)

ok "OS: $OS_ID $OS_VER"
ok "Kernel: $KERNEL"
ok "Interface: $IFACE | IP: $SERVER_IP"
ok "Resources: ${CPU_CORES} cores / ${RAM_GB}GB RAM"

# XDP support check (kernel >= 5.6)
XDP_SUPPORTED=false
if [ "$KERNEL_MAJOR" -gt 5 ] || { [ "$KERNEL_MAJOR" -eq 5 ] && [ "$KERNEL_MINOR" -ge 6 ]; }; then
  XDP_SUPPORTED=true
  ok "XDP/eBPF: Supported"
else
  warn "XDP/eBPF: NOT supported (kernel $KERNEL below 5.6)"
fi

# ── Gather Config ─────────────────────────────────────────────────
step "Configuration Questions"
echo -e "${DIM}Press Enter to accept the default value shown in [brackets]${RESET}"
echo ""

askd "Panel domain (e.g. panel.sparrowx.net):"    DOMAIN         "localhost"
askd "Panel port:"                                 PANEL_PORT     "3001"
askd "Supabase URL:"                               SUPABASE_URL   ""
askd "Supabase Anon Key:"                          SUPABASE_ANON  ""
askd "Supabase Service Key:"                       SUPABASE_SVC   ""
askd "Discord webhook URL (for alerts):"           DISCORD_URL    ""
askd "Admin email:"                                ADMIN_EMAIL    "admin@localhost"

echo ""
info "Starting automated deployment..."
sleep 1

# ── System Update & Base Packages ────────────────────────────────
step "Installing Dependencies"
apt-get update -qq | tee -a "$LOG_FILE"
apt-get install -y -qq \
  curl wget git unzip jq net-tools \
  nftables wireguard haproxy \
  build-essential clang llvm libelf-dev libbpf-dev \
  linux-headers-$(uname -r) bpftool | tee -a "$LOG_FILE"
ok "System packages installed"

# Node.js
if ! command -v node &>/dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - | tee -a "$LOG_FILE"
  apt-get install -y nodejs | tee -a "$LOG_FILE"
fi
ok "Node.js $(node -v)"

# PM2
if ! command -v pm2 &>/dev/null; then
  npm install -g pm2 --silent
fi
ok "PM2 installed"

# ── Write .env ────────────────────────────────────────────────────
step "Configuring Environment"
cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by sparrow-setup.sh on $(date)
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON}
SUPABASE_SERVICE_KEY=${SUPABASE_SVC}
SPARROWX_DOMAIN=${DOMAIN}
PORT=${PANEL_PORT}
ADMIN_EMAIL=${ADMIN_EMAIL}
DISCORD_WEBHOOK_URL=${DISCORD_URL}
NODE_ENV=production
EOF
ok ".env file written"

# ── Layer 2: nftables ─────────────────────────────────────────────
step "Layer 2: Setting Up nftables"
if [ -f "$SCRIPT_DIR/configs/nftables-sparrowx.conf" ]; then
  sed "s/IFACE_PLACEHOLDER/$IFACE/g" "$SCRIPT_DIR/configs/nftables-sparrowx.conf" > /etc/nftables.conf.sparrowx
  # Non-destructive include
  if ! grep -q "nftables.conf.sparrowx" /etc/nftables.conf; then
     echo "include \"/etc/nftables.conf.sparrowx\"" >> /etc/nftables.conf
  fi
  nft -f /etc/nftables.conf.sparrowx 2>>"$LOG_FILE" && ok "Rules applied" || warn "Rules failed"
else
  warn "nftables config source missing"
fi

# ── sysctl: Hardening ─────────────────────────────────────────────
step "Layer 2: Kernel Hardening"
if [ -f "$SCRIPT_DIR/configs/sysctl-sparrowx.conf" ]; then
  cp "$SCRIPT_DIR/configs/sysctl-sparrowx.conf" /etc/sysctl.d/99-sparrowx.conf
  sysctl -p /etc/sysctl.d/99-sparrowx.conf >> "$LOG_FILE" 2>&1 && ok "Kernel hardened"
fi

# ── Layer 3: HAProxy ─────────────────────────────────────────────
step "Layer 3: HAProxy WAF"
mkdir -p /etc/haproxy/certs
if [ -f "$SCRIPT_DIR/configs/haproxy.cfg" ]; then
  sed "s/PANEL_PORT_PLACEHOLDER/$PANEL_PORT/g" "$SCRIPT_DIR/configs/haproxy.cfg" > /etc/haproxy/haproxy.cfg
  systemctl enable haproxy
  systemctl restart haproxy >> "$LOG_FILE" 2>&1 && ok "HAProxy running" || warn "HAProxy failed to start"
fi

# ── Layer 4: FastNetMon ──────────────────────────────────────────
step "Layer 4: FastNetMon Detection"
if ! command -v fastnetmon &>/dev/null; then
  wget -q https://install.fastnetmon.com/installer -O /tmp/fnm_install.sh
  bash /tmp/fnm_install.sh --install-only >> "$LOG_FILE" 2>&1
fi

if [ -f "$SCRIPT_DIR/configs/fastnetmon.conf" ]; then
  sed "s/IFACE_PLACEHOLDER/$IFACE/g" "$SCRIPT_DIR/configs/fastnetmon.conf" > /etc/fastnetmon.conf
  cp "$SCRIPT_DIR/configs/fastnetmon-notify.sh" /usr/local/bin/fastnetmon-notify.sh
  chmod +x /usr/local/bin/fastnetmon-notify.sh
  systemctl enable fastnetmon
  systemctl restart fastnetmon >> "$LOG_FILE" 2>&1 && ok "FastNetMon active" || warn "FastNetMon failed (Check logs)"
fi

# ── Layer 1: XDP/eBPF ────────────────────────────────────────────
if [ "$XDP_SUPPORTED" = true ]; then
  step "Layer 1: XDP Packet Filter"
  cd "$SCRIPT_DIR/xdp"
  # Compile with BTF support (-g)
  clang -O2 -g -target bpf \
    -D__TARGET_ARCH_$(uname -m | sed 's/x86_64/x86/') \
    -I/usr/include/$(uname -m)-linux-gnu \
    -c sparrowx_xdp.c -o sparrowx_xdp.o >> "$LOG_FILE" 2>&1
  
  if [ -f "sparrowx_xdp.o" ]; then
    bash load_xdp.sh >> "$LOG_FILE" 2>&1 && ok "XDP attached to $IFACE" || warn "XDP load failed"
  else
    warn "XDP compilation failed"
  fi
  cd "$SCRIPT_DIR"
fi

# ── Finalize Panel ────────────────────────────────────────────────
step "Finalizing Panel"
npm install --silent >> "$LOG_FILE" 2>&1
pm2 delete sparrowx-panel 2>/dev/null || true
pm2 start ecosystem.config.js >> "$LOG_FILE" 2>&1
pm2 save >> "$LOG_FILE" 2>&1
ok "SparrowX services started"

# CLI link
ln -sf "$SCRIPT_DIR/sparrow.sh" /usr/local/bin/sparrow
ok "Sparrow CLI installed"

# Watchdog
CRON_WATCHDOG="*/5 * * * * root bash $SCRIPT_DIR/sbs-watchdog.sh >> /var/log/sbs/watchdog.log 2>&1"
echo "$CRON_WATCHDOG" > /etc/cron.d/sparrowx-watchdog
ok "Watchdog cron job scheduled"

# ── Results ───────────────────────────────────────────────────────
step "Setup Complete!"
echo -e "  ${GREEN}All layers have been configured and applied.${RESET}"
echo -e "  Run ${BOLD}sparrow${RESET} to manage your server."
echo ""
