#!/bin/bash
# =================================================================
#  SPARROWX — Universal Auto-Setup Installer
#  Works on: Ubuntu 20.04+ / Debian 11+
#
#  Usage: bash sparrow-setup.sh
#  Run after: git clone <repo> /opt/sbs && cd /opt/sbs
# =================================================================
set -u

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; RESET='\033[0m'

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOG_FILE="$SCRIPT_DIR/setup.log"

# ── Helpers ───────────────────────────────────────────────────────
log()  { echo -e "$1" | tee -a "$LOG_FILE"; }
ok()   { log "${GREEN}[✓] $1${RESET}"; }
info() { log "${CYAN}[→] $1${RESET}"; }
warn() { log "${YELLOW}[!] $1${RESET}"; }
err()  { log "${RED}[✗] $1${RESET}"; }
ask()  { echo -ne "${BOLD}$1${RESET} "; read -r "$2"; }
askd() { echo -ne "${BOLD}$1${RESET} ${DIM}[${3}]${RESET} "; read -r "$2"; eval "$2=\${$2:-$3}"; }

banner() {
  clear
  echo -e "${CYAN}${BOLD}"
  echo "  ╔══════════════════════════════════════════════════════╗"
  echo "  ║     SPARROWX — Universal Defense Stack Installer     ║"
  echo "  ║     Supports: Ubuntu 20.04+ / Debian 11+            ║"
  echo "  ╚══════════════════════════════════════════════════════╝"
  echo -e "${RESET}"
}

step() {
  echo ""
  echo -e "${CYAN}${BOLD}━━━ $1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
}

# ── Root check ────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run as root: sudo bash sparrow-setup.sh${RESET}"
  exit 1
fi

banner

# ── OS Detection ──────────────────────────────────────────────────
step "Detecting System"
OS_ID=$(grep '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
OS_VER=$(grep '^VERSION_ID=' /etc/os-release | cut -d= -f2 | tr -d '"')
KERNEL=$(uname -r)
ARCH=$(uname -m)
IFACE=$(ip route | grep default | awk '{print $5}' | head -1)
SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
RAM_GB=$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo)
CPU_CORES=$(nproc)
KERNEL_MAJOR=$(echo "$KERNEL" | cut -d. -f1)
KERNEL_MINOR=$(echo "$KERNEL" | cut -d. -f2)

ok "OS: $OS_ID $OS_VER"
ok "Kernel: $KERNEL"
ok "Interface: $IFACE | IP: $SERVER_IP"
ok "Resources: ${CPU_CORES} cores / ${RAM_GB}GB RAM"

# XDP support check (kernel >= 5.6)
XDP_SUPPORTED=false
if [ "$KERNEL_MAJOR" -gt 5 ] || { [ "$KERNEL_MAJOR" -eq 5 ] && [ "$KERNEL_MINOR" -ge 6 ]; }; then
  XDP_SUPPORTED=true
  ok "XDP/eBPF: Supported (kernel $KERNEL)"
else
  warn "XDP/eBPF: NOT supported (kernel $KERNEL is below 5.6) — Layer 1 will be skipped"
fi

# ── Gather Config ─────────────────────────────────────────────────
step "Configuration Questions"
echo -e "${DIM}Press Enter to accept the default value shown in [brackets]${RESET}"
echo ""

askd "Panel domain (e.g. panel.sparrowx.net):"    DOMAIN         "localhost"
askd "Panel port:"                                 PANEL_PORT     "3001"
askd "Supabase URL:"                               SUPABASE_URL   ""
askd "Supabase Anon Key:"                          SUPABASE_ANON  ""
askd "Supabase Service Key:"                       SUPABASE_SVC   ""
askd "Discord webhook URL (leave blank to skip):"  DISCORD_URL    ""
askd "Admin email:"                                ADMIN_EMAIL    "admin@localhost"

echo ""
echo -e "${BOLD}Select layers to install:${RESET}"
askd "Install HAProxy (Layer 3 WAF)? [y/n]:"       INSTALL_HAPROXY    "y"
askd "Install FastNetMon (Layer 4 detection)? [y/n]:" INSTALL_FNM      "y"
askd "Install XDP/eBPF (Layer 1 wire-speed)? [y/n]:"  INSTALL_XDP     "$( [ "$XDP_SUPPORTED" = true ] && echo y || echo n )"
askd "Setup SSL with Certbot? [y/n]:"              INSTALL_SSL        "y"
askd "Install Prometheus + Grafana monitoring? [y/n]:" INSTALL_MONITOR "n"

echo ""
info "Configuration complete. Starting installation..."
sleep 1

# ── System Update & Base Packages ────────────────────────────────
step "Installing Base Packages"
apt-get update -qq | tee -a "$LOG_FILE"
apt-get install -y -qq \
  curl wget git unzip jq net-tools \
  nftables wireguard \
  build-essential | tee -a "$LOG_FILE"
ok "Base packages installed"

# ── Node.js ──────────────────────────────────────────────────────
step "Installing Node.js"
if ! command -v node &>/dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash - | tee -a "$LOG_FILE"
  apt-get install -y nodejs | tee -a "$LOG_FILE"
fi
ok "Node.js $(node -v)"

# PM2
if ! command -v pm2 &>/dev/null; then
  npm install -g pm2 --silent
fi
ok "PM2 $(pm2 -v)"

# ── Write .env ────────────────────────────────────────────────────
step "Writing .env File"
cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by sparrow-setup.sh on $(date)
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${SUPABASE_ANON}
SUPABASE_SERVICE_KEY=${SUPABASE_SVC}
SPARROWX_DOMAIN=${DOMAIN}
PORT=${PANEL_PORT}
ADMIN_EMAIL=${ADMIN_EMAIL}
DISCORD_WEBHOOK_URL=${DISCORD_URL}
NODE_ENV=production
EOF
ok ".env written"

# ── npm Install ───────────────────────────────────────────────────
step "Installing Node Dependencies"
cd "$SCRIPT_DIR"
npm install --silent | tee -a "$LOG_FILE"
ok "npm packages installed"

# Build frontend if src exists
if [ -d "$SCRIPT_DIR/frontend/src" ]; then
  info "Building frontend..."
  cd "$SCRIPT_DIR/frontend"
  npm install --silent | tee -a "$LOG_FILE"
  npm run build --silent | tee -a "$LOG_FILE"
  cd "$SCRIPT_DIR"
  ok "Frontend built"
fi

# ── nftables (Layer 2) ────────────────────────────────────────────
step "Setting Up nftables (Layer 2)"
mkdir -p /var/log/sbs

if [ -f "$SCRIPT_DIR/configs/nftables-sparrowx.conf" ]; then
  # Replace placeholder interface name with detected one
  sed "s/IFACE_PLACEHOLDER/$IFACE/g" "$SCRIPT_DIR/configs/nftables-sparrowx.conf" \
    > /etc/nftables.conf
  nft -f /etc/nftables.conf 2>>"$LOG_FILE" && ok "nftables rules applied" || warn "nftables apply failed — check $LOG_FILE"
  systemctl enable nftables
else
  # Minimal fallback ruleset
  cat > /etc/nftables.conf <<'NFTEOF'
#!/usr/sbin/nft -f
flush ruleset
table inet sparrowx_shield {
  set blacklist { type ipv4_addr; flags dynamic, timeout; timeout 1h; }
  chain input {
    type filter hook input priority 0; policy accept;
    iif "lo" accept
    ct state established,related accept
    ip saddr @blacklist drop
    tcp flags syn limit rate over 200/second burst 100 packets \
      add @blacklist { ip saddr } drop
    tcp dport { 22, PANEL_PORT } accept
  }
}
NFTEOF
  sed -i "s/PANEL_PORT/$PANEL_PORT/g" /etc/nftables.conf
  nft -f /etc/nftables.conf 2>>"$LOG_FILE" && ok "Minimal nftables ruleset applied" || warn "nftables apply failed"
  systemctl enable nftables
fi

# ── sysctl hardening ──────────────────────────────────────────────
step "Applying Kernel Hardening (sysctl)"
if [ -f "$SCRIPT_DIR/configs/sysctl-sparrowx.conf" ]; then
  cp "$SCRIPT_DIR/configs/sysctl-sparrowx.conf" /etc/sysctl.d/99-sparrowx.conf
else
  cat > /etc/sysctl.d/99-sparrowx.conf <<'EOF'
# SparrowX kernel hardening
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.ip_forward = 1
net.core.somaxconn = 65535
net.core.netdev_max_backlog = 65535
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15
EOF
fi
sysctl -p /etc/sysctl.d/99-sparrowx.conf >> "$LOG_FILE" 2>&1
ok "Kernel hardening applied"

# ── HAProxy (Layer 3) ─────────────────────────────────────────────
if [ "$INSTALL_HAPROXY" = "y" ] || [ "$INSTALL_HAPROXY" = "Y" ]; then
  step "Installing HAProxy (Layer 3)"
  apt-get install -y haproxy | tee -a "$LOG_FILE"

  if [ -f "$SCRIPT_DIR/configs/haproxy.cfg" ]; then
    sed "s/PANEL_PORT_PLACEHOLDER/$PANEL_PORT/g; s/DOMAIN_PLACEHOLDER/$DOMAIN/g" \
      "$SCRIPT_DIR/configs/haproxy.cfg" > /etc/haproxy/haproxy.cfg
  else
    cat > /etc/haproxy/haproxy.cfg <<EOF
global
  log /dev/log local0
  maxconn 50000
  user haproxy
  group haproxy
  daemon

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5s
  timeout client  30s
  timeout server  30s

frontend sparrowx_front
  bind *:80
  bind *:443 ssl crt /etc/haproxy/cert.pem
  http-request track-sc0 src table sparrowx_rate
  http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
  # Block bad bots
  acl bad_agent hdr_sub(user-agent) -i sqlmap nikto masscan zgrab nuclei
  http-request deny if bad_agent
  default_backend sparrowx_panel

backend sparrowx_rate
  stick-table type ip size 100k expire 60s store http_req_rate(10s)

backend sparrowx_panel
  server panel 127.0.0.1:${PANEL_PORT} check
EOF
  fi

  haproxy -c -f /etc/haproxy/haproxy.cfg >> "$LOG_FILE" 2>&1 && ok "HAProxy config valid" || warn "HAProxy config issue — check $LOG_FILE"
  systemctl stop nginx 2>/dev/null || true
  systemctl disable nginx 2>/dev/null || true
  systemctl enable --now haproxy
  ok "HAProxy running"
fi

# ── FastNetMon (Layer 4) ──────────────────────────────────────────
if [ "$INSTALL_FNM" = "y" ] || [ "$INSTALL_FNM" = "Y" ]; then
  step "Installing FastNetMon (Layer 4)"
  if ! command -v fastnetmon &>/dev/null; then
    wget -q https://install.fastnetmon.com/installer -O /tmp/fnm_install.sh
    bash /tmp/fnm_install.sh >> "$LOG_FILE" 2>&1
  fi

  if [ -f "$SCRIPT_DIR/configs/fastnetmon-notify.sh" ]; then
    cp "$SCRIPT_DIR/configs/fastnetmon-notify.sh" /usr/local/bin/fastnetmon-notify.sh
    chmod +x /usr/local/bin/fastnetmon-notify.sh
    ok "FastNetMon notify script installed"
  fi

  if [ -f "$SCRIPT_DIR/configs/fastnetmon.conf" ]; then
    cp "$SCRIPT_DIR/configs/fastnetmon.conf" /etc/fastnetmon.conf
    systemctl enable --now fastnetmon 2>/dev/null || true
    ok "FastNetMon configured"
  else
    warn "FastNetMon config not found in configs/ — install manually"
  fi
fi

# ── XDP/eBPF (Layer 1) ────────────────────────────────────────────
if { [ "$INSTALL_XDP" = "y" ] || [ "$INSTALL_XDP" = "Y" ]; } && [ "$XDP_SUPPORTED" = true ]; then
  step "Setting Up XDP/eBPF (Layer 1)"
  apt-get install -y -qq clang llvm libelf-dev libbpf-dev \
    linux-headers-$(uname -r) bpftool 2>>"$LOG_FILE" || true

  if [ -f "$SCRIPT_DIR/xdp/sparrowx_xdp.c" ]; then
    cd "$SCRIPT_DIR/xdp"
    clang -O2 -target bpf -c sparrowx_xdp.c -o sparrowx_xdp.o 2>>"$LOG_FILE" \
      && ok "XDP program compiled" \
      || warn "XDP compile failed — check $LOG_FILE"
    bash "$SCRIPT_DIR/xdp/load_xdp.sh" 2>>"$LOG_FILE" \
      && ok "XDP attached to $IFACE" \
      || warn "XDP attach failed"
    cd "$SCRIPT_DIR"
  else
    warn "XDP source not found — push xdp/sparrowx_xdp.c first"
  fi
elif [ "$INSTALL_XDP" = "y" ] && [ "$XDP_SUPPORTED" = false ]; then
  warn "XDP skipped — kernel $KERNEL does not support it (need 5.6+)"
fi

# ── SSL (Certbot) ─────────────────────────────────────────────────
if [ "$INSTALL_SSL" = "y" ] && [ "$DOMAIN" != "localhost" ]; then
  step "Setting Up SSL"
  apt-get install -y certbot | tee -a "$LOG_FILE"
  certbot certonly --standalone -d "$DOMAIN" --non-interactive \
    --agree-tos --email "$ADMIN_EMAIL" \
    --pre-hook "systemctl stop haproxy" \
    --post-hook "systemctl start haproxy" 2>>"$LOG_FILE" \
    && ok "SSL certificate obtained for $DOMAIN" \
    || warn "SSL failed — check domain DNS points to $SERVER_IP"
fi

# ── PM2 Panel Start ───────────────────────────────────────────────
step "Starting SparrowX Panel"
cd "$SCRIPT_DIR"
pm2 delete sparrowx-panel 2>/dev/null || true
pm2 delete sparrow-brain  2>/dev/null || true
pm2 start ecosystem.config.js 2>>"$LOG_FILE"
pm2 save 2>>"$LOG_FILE"
pm2 startup 2>>"$LOG_FILE" | tail -1 | bash 2>/dev/null || true
ok "PM2 processes started"

# ── Sparrow CLI ───────────────────────────────────────────────────
step "Installing Sparrow CLI"
chmod +x "$SCRIPT_DIR/sparrow.sh"
ln -sf "$SCRIPT_DIR/sparrow.sh" /usr/local/bin/sparrow
ok "sparrow command installed — run 'sparrow' from anywhere"

# ── Cron Jobs ─────────────────────────────────────────────────────
step "Setting Up Cron Jobs"
CRON_DISK="0 3 1 * * root bash $SCRIPT_DIR/sbs-disk-manager.sh auto >> /var/log/sbs/disk-manager.log 2>&1"
CRON_BRAIN="0 * * * * root node $SCRIPT_DIR/sparrow-brain.js --apply >> /var/log/sbs/brain.log 2>&1"
echo "$CRON_DISK"  > /etc/cron.d/sparrowx-disk
echo "$CRON_BRAIN" > /etc/cron.d/sparrowx-brain
chmod 644 /etc/cron.d/sparrowx-disk /etc/cron.d/sparrowx-brain
ok "Cron: disk manager runs 1st of month at 3am"
ok "Cron: brain learning runs every hour"

# ── Monitoring ────────────────────────────────────────────────────
if [ "$INSTALL_MONITOR" = "y" ] || [ "$INSTALL_MONITOR" = "Y" ]; then
  step "Installing Prometheus + Grafana"
  # Prometheus
  wget -qO /tmp/prometheus.tar.gz \
    https://github.com/prometheus/prometheus/releases/download/v2.51.0/prometheus-2.51.0.linux-amd64.tar.gz
  tar xf /tmp/prometheus.tar.gz -C /opt/
  ln -sf /opt/prometheus-*/prometheus /usr/local/bin/prometheus
  ok "Prometheus installed"
  # Grafana
  wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key
  echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" \
    > /etc/apt/sources.list.d/grafana.list
  apt-get update -qq && apt-get install -y grafana | tee -a "$LOG_FILE"
  systemctl enable --now grafana-server
  ok "Grafana running on port 3000"
fi

# ── Final Status Report ───────────────────────────────────────────
step "Setup Complete — Status Report"
echo ""
echo -e "  ${BOLD}Server IP:${RESET}      $SERVER_IP"
echo -e "  ${BOLD}Domain:${RESET}         $DOMAIN"
echo -e "  ${BOLD}Panel Port:${RESET}     $PANEL_PORT"
echo -e "  ${BOLD}Interface:${RESET}      $IFACE"
echo ""

echo -e "  ${BOLD}Defense Layers:${RESET}"
if [ "$INSTALL_XDP" = "y" ] && [ "$XDP_SUPPORTED" = true ]; then
  echo -e "    Layer 1 — XDP/eBPF    $(ip link show $IFACE 2>/dev/null | grep -q xdp && echo "${GREEN}ACTIVE${RESET}" || echo "${YELLOW}PENDING${RESET}")"
else
  echo -e "    Layer 1 — XDP/eBPF    ${DIM}SKIPPED${RESET}"
fi
echo -e "    Layer 2 — nftables    $(nft list ruleset 2>/dev/null | grep -q sparrowx && echo "${GREEN}ACTIVE${RESET}" || echo "${YELLOW}CHECK${RESET}")"
if [ "$INSTALL_HAPROXY" = "y" ]; then
  echo -e "    Layer 3 — HAProxy     $(systemctl is-active haproxy 2>/dev/null | grep -q active && echo "${GREEN}ACTIVE${RESET}" || echo "${YELLOW}CHECK${RESET}")"
else
  echo -e "    Layer 3 — HAProxy     ${DIM}SKIPPED${RESET}"
fi
if [ "$INSTALL_FNM" = "y" ]; then
  echo -e "    Layer 4 — FastNetMon  $(systemctl is-active fastnetmon 2>/dev/null | grep -q active && echo "${GREEN}ACTIVE${RESET}" || echo "${YELLOW}CHECK${RESET}")"
else
  echo -e "    Layer 4 — FastNetMon  ${DIM}SKIPPED${RESET}"
fi

echo ""
echo -e "  ${BOLD}Panel:${RESET}"
echo -e "    $(pm2 list 2>/dev/null | grep sparrowx && echo "${GREEN}Running${RESET}" || echo "${YELLOW}Check pm2 status${RESET}")"

echo ""
echo -e "  ${GREEN}${BOLD}Next steps:${RESET}"
echo -e "    sparrow inspect          — verify dashboard data"
echo -e "    sparrow brain analyze    — run first threat analysis"
echo -e "    sparrow                  — open full control menu"
echo ""
echo -e "  ${DIM}Full setup log: $LOG_FILE${RESET}"
echo ""
